// Test MongoDB URI format
console.log('MongoDB URI Examples:')
console.log('')
console.log('1. Local MongoDB:')
console.log('   MONGODB_URI="mongodb://localhost:27017/amazing-grace-church"')
console.log('')
console.log('2. MongoDB Atlas (Cloud):')
console.log('   MONGODB_URI="mongodb+srv://username:password@cluster0.xxxxx.mongodb.net/amazing-grace-church?retryWrites=true&w=majority"')
console.log('')
console.log('3. Complete .env.local file:')
console.log('   MONGODB_URI="mongodb+srv://amazing-grace-admin:your-password@cluster0.abc123.mongodb.net/amazing-grace-church?retryWrites=true&w=majority"')
console.log('   NEXTAUTH_SECRET="amazing-grace-church-secret-key-2024"')
console.log('   NEXTAUTH_URL="http://localhost:3000"')
console.log('   ADMIN_EMAIL="admin@amazinggracechurch.org"')
console.log('   ADMIN_PASSWORD="grace1234"')
console.log('')
console.log('Steps to get MongoDB Atlas URI:')
console.log('1. Go to https://www.mongodb.com/atlas')
console.log('2. Create free account and cluster')
console.log('3. Create database user (username/password)')
console.log('4. Whitelist your IP address')
console.log('5. Get connection string from "Connect" button')
console.log('6. Replace <password> with your actual password')
console.log('7. Replace <dbname> with "amazing-grace-church"')
